var express = require('express')
var app = express()
var mysql = require('mysql')

var con = mysql.createConnection({
	host     : 'localhost',
	user     : 'top4ek',
	password : 'q2w3e4r5',
	database : 'food'
});

var data = `[
  {
    "food_name": "Спаржа",
    "Calories": 20,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 1,
    "Dietary Fiber": 8,
    "Sugars": 2,
    "Protein": 2,
    "Vitamin A": 10,
    "Vitamin C": 15,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Перец болгарский",
    "Calories": 25,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 2,
    "Potassium": 6,
    "total_carbohydrate": 2,
    "Dietary Fiber": 8,
    "Sugars": 4,
    "Protein": 1,
    "Vitamin A": 4,
    "Vitamin C": 190,
    "Calcium": 2,
    "تتIronتت": 4,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Брокколи",
    "Calories": 45,
    "Caloriesتfrom Fat": 0,
    "total_fat": 1,
    "Sodium": 3,
    "Potassium": 13,
    "total_carbohydrate": 3,
    "Dietary Fiber": 12,
    "Sugars": 2,
    "Protein": 4,
    "Vitamin A": 6,
    "Vitamin C": 220,
    "Calcium": 6,
    "تتIronتت": 6,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Морковь",
    "Calories": 30,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 3,
    "Potassium": 7,
    "total_carbohydrate": 2,
    "Dietary Fiber": 8,
    "Sugars": 5,
    "Protein": 1,
    "Vitamin A": 110,
    "Vitamin C": 10,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Цветная капуста 1/6 среднего кочана (99 г/3.5 унций)",
    "Calories": 25,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 8,
    "total_carbohydrate": 2,
    "Dietary Fiber": 8,
    "Sugars": 2,
    "Protein": 2,
    "Vitamin A": 0,
    "Vitamin C": 100,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Сельдерея",
    "Calories": 15,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 5,
    "Potassium": 7,
    "total_carbohydrate": 1,
    "Dietary Fiber": 8,
    "Sugars": 2,
    "Protein": 0,
    "Vitamin A": 10,
    "Vitamin C": 15,
    "Calcium": 4,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Огурец",
    "Calories": 10,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 4,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 1,
    "Protein": 1,
    "Vitamin A": 4,
    "Vitamin C": 10,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Зеленая (Щелчковая) фасоль",
    "Calories": 20,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 6,
    "total_carbohydrate": 2,
    "Dietary Fiber": 12,
    "Sugars": 2,
    "Protein": 1,
    "Vitamin A": 4,
    "Vitamin C": 10,
    "Calcium": 4,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "GreenتCabbage",
    "Calories": 25,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 5,
    "total_carbohydrate": 2,
    "Dietary Fiber": 8,
    "Sugars": 3,
    "Protein": 1,
    "Vitamin A": 0,
    "Vitamin C": 70,
    "Calcium": 4,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Зеленый лук",
    "Calories": 10,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 2,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 1,
    "Protein": 0,
    "Vitamin A": 2,
    "Vitamin C": 8,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Салат айсберг",
    "Calories": 10,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 4,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 2,
    "Protein": 1,
    "Vitamin A": 6,
    "Vitamin C": 6,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Листовой салат",
    "Calories": 15,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 5,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 1,
    "Protein": 1,
    "Vitamin A": 130,
    "Vitamin C": 6,
    "Calcium": 2,
    "تتIronتت": 4,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Грибов",
    "Calories": 20,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 9,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 0,
    "Protein": 3,
    "Vitamin A": 0,
    "Vitamin C": 2,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Лук репчатый",
    "Calories": 45,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 5,
    "total_carbohydrate": 4,
    "Dietary Fiber": 12,
    "Sugars": 9,
    "Protein": 1,
    "Vitamin A": 0,
    "Vitamin C": 20,
    "Calcium": 4,
    "تتIronتت": 4,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Картофель",
    "Calories": 110,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 18,
    "total_carbohydrate": 9,
    "Dietary Fiber": 8,
    "Sugars": 1,
    "Protein": 3,
    "Vitamin A": 0,
    "Vitamin C": 45,
    "Calcium": 2,
    "تتIronتت": 6,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Редис",
    "Calories": 10,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 2,
    "Potassium": 5,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 2,
    "Protein": 0,
    "Vitamin A": 0,
    "Vitamin C": 30,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "SummerتSquash",
    "Calories": 20,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 1,
    "Dietary Fiber": 8,
    "Sugars": 2,
    "Protein": 1,
    "Vitamin A": 6,
    "Vitamin C": 30,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Сладкая кукуруза",
    "Calories": 90,
    "Caloriesتfrom Fat": 20,
    "total_fat": 4,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 6,
    "Dietary Fiber": 8,
    "Sugars": 5,
    "Protein": 4,
    "Vitamin A": 2,
    "Vitamin C": 10,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Сладкий картофель",
    "Calories": 100,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 3,
    "Potassium": 13,
    "total_carbohydrate": 8,
    "Dietary Fiber": 16,
    "Sugars": 7,
    "Protein": 2,
    "Vitamin A": 120,
    "Vitamin C": 30,
    "Calcium": 4,
    "تتIronتت": 4,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Помидор",
    "Calories": 25,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 10,
    "total_carbohydrate": 2,
    "Dietary Fiber": 4,
    "Sugars": 3,
    "Protein": 1,
    "Vitamin A": 20,
    "Vitamin C": 40,
    "Calcium": 2,
    "تتIronتت": 4,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Vegetables, Serving Size (gram weight/تounce weight)"
  },
  {
    "food_name": "Яблоко",
    "Calories": 130,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 11,
    "Dietary Fiber": 20,
    "Sugars": 25,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 8,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Авокадо",
    "Calories": 50,
    "Caloriesتfrom Fat": 35,
    "total_fat": 7,
    "Sodium": 0,
    "Potassium": 4,
    "total_carbohydrate": 1,
    "Dietary Fiber": 4,
    "Sugars": 0,
    "Protein": 1,
    "Vitamin A": 0,
    "Vitamin C": 4,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Банан",
    "Calories": 110,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 13,
    "total_carbohydrate": 10,
    "Dietary Fiber": 12,
    "Sugars": 19,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 15,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Дыня",
    "Calories": 50,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 7,
    "total_carbohydrate": 4,
    "Dietary Fiber": 4,
    "Sugars": 11,
    "Protein": 1,
    "Vitamin A": 120,
    "Vitamin C": 80,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Грейпфрут",
    "Calories": 60,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 5,
    "total_carbohydrate": 5,
    "Dietary Fiber": 8,
    "Sugars": 11,
    "Protein": 1,
    "Vitamin A": 35,
    "Vitamin C": 100,
    "Calcium": 4,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Винограда",
    "Calories": 90,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 7,
    "total_carbohydrate": 8,
    "Dietary Fiber": 4,
    "Sugars": 20,
    "Protein": 0,
    "Vitamin A": 0,
    "Vitamin C": 2,
    "Calcium": 2,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "HoneydewتMelon 1/10 mediumتmelon (134 г/4.8 УНЦ.)",
    "Calories": 50,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 1,
    "Potassium": 6,
    "total_carbohydrate": 4,
    "Dietary Fiber": 4,
    "Sugars": 11,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 45,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Киви",
    "Calories": 90,
    "Caloriesتfrom Fat": 10,
    "total_fat": 2,
    "Sodium": 0,
    "Potassium": 13,
    "total_carbohydrate": 7,
    "Dietary Fiber": 16,
    "Sugars": 13,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 240,
    "Calcium": 4,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Лимон",
    "Calories": 15,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 2,
    "total_carbohydrate": 2,
    "Dietary Fiber": 8,
    "Sugars": 2,
    "Protein": 0,
    "Vitamin A": 0,
    "Vitamin C": 40,
    "Calcium": 2,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Известь",
    "Calories": 20,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 2,
    "total_carbohydrate": 2,
    "Dietary Fiber": 8,
    "Sugars": 0,
    "Protein": 0,
    "Vitamin A": 0,
    "Vitamin C": 35,
    "Calcium": 0,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Нектарин",
    "Calories": 60,
    "Caloriesتfrom Fat": 5,
    "total_fat": 1,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 5,
    "Dietary Fiber": 8,
    "Sugars": 11,
    "Protein": 1,
    "Vitamin A": 8,
    "Vitamin C": 15,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Апельсин",
    "Calories": 80,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 6,
    "Dietary Fiber": 12,
    "Sugars": 14,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 130,
    "Calcium": 6,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Персик",
    "Calories": 60,
    "Caloriesتfrom Fat": 0,
    "total_fat": 1,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 5,
    "Dietary Fiber": 8,
    "Sugars": 13,
    "Protein": 1,
    "Vitamin A": 6,
    "Vitamin C": 15,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Груша",
    "Calories": 100,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 5,
    "total_carbohydrate": 9,
    "Dietary Fiber": 24,
    "Sugars": 16,
    "Protein": 1,
    "Vitamin A": 0,
    "Vitamin C": 10,
    "Calcium": 2,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Ананас",
    "Calories": 50,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 3,
    "total_carbohydrate": 4,
    "Dietary Fiber": 4,
    "Sugars": 10,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 50,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Чернослива",
    "Calories": 70,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 7,
    "total_carbohydrate": 6,
    "Dietary Fiber": 8,
    "Sugars": 16,
    "Protein": 1,
    "Vitamin A": 8,
    "Vitamin C": 10,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Клубника",
    "Calories": 50,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 5,
    "total_carbohydrate": 4,
    "Dietary Fiber": 8,
    "Sugars": 8,
    "Protein": 1,
    "Vitamin A": 0,
    "Vitamin C": 160,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "SweetتCherries 21 черешни;Кубок ت1",
    "Calories": 100,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 10,
    "total_carbohydrate": 9,
    "Dietary Fiber": 4,
    "Sugars": 16,
    "Protein": 1,
    "Vitamin A": 2,
    "Vitamin C": 15,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Мандарин",
    "Calories": 50,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 5,
    "total_carbohydrate": 4,
    "Dietary Fiber": 8,
    "Sugars": 9,
    "Protein": 1,
    "Vitamin A": 6,
    "Vitamin C": 45,
    "Calcium": 4,
    "تتIronتت": 0,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "Арбуз",
    "Calories": 80,
    "Caloriesتfrom Fat": 0,
    "total_fat": 0,
    "Sodium": 0,
    "Potassium": 8,
    "total_carbohydrate": 7,
    "Dietary Fiber": 4,
    "Sugars": 20,
    "Protein": 1,
    "Vitamin A": 30,
    "Vitamin C": 25,
    "Calcium": 2,
    "تتIronتت": 4,
    "Saturated Fat": "",
    "Chole-sterol": "",
    "Food Type": "Fruits ServingتSize (gramتweight/ounceتweight)"
  },
  {
    "food_name": "синий краб",
    "Calories": 100,
    "Caloriesتfrom Fat": 10,
    "total_fat": 2,
    "Sodium": 14,
    "Potassium": 9,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 20,
    "Vitamin A": 0,
    "Vitamin C": 4,
    "Calcium": 10,
    "تتIronتت": 4,
    "Saturated Fat": 0,
    "Chole-sterol": 32,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Сом",
    "Calories": 130,
    "Caloriesتfrom Fat": 60,
    "total_fat": 9,
    "Sodium": 2,
    "Potassium": 7,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 17,
    "Vitamin A": 0,
    "Vitamin C": 0,
    "Calcium": 0,
    "تتIronتت": 0,
    "Saturated Fat": 10,
    "Chole-sterol": 17,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Моллюсков",
    "Calories": 110,
    "Caloriesتfrom Fat": 15,
    "total_fat": 2,
    "Sodium": 4,
    "Potassium": 13,
    "total_carbohydrate": 2,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 17,
    "Vitamin A": 10,
    "Vitamin C": 0,
    "Calcium": 8,
    "تتIronتت": 30,
    "Saturated Fat": 0,
    "Chole-sterol": 27,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Треска",
    "Calories": 90,
    "Caloriesتfrom Fat": 5,
    "total_fat": 2,
    "Sodium": 3,
    "Potassium": 13,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 20,
    "Vitamin A": 0,
    "Vitamin C": 2,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": 0,
    "Chole-sterol": 17,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Камбала / Подошва",
    "Calories": 100,
    "Caloriesتfrom Fat": 15,
    "total_fat": 2,
    "Sodium": 4,
    "Potassium": 11,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 19,
    "Vitamin A": 0,
    "Vitamin C": 0,
    "Calcium": 2,
    "تتIronتت": 0,
    "Saturated Fat": 0,
    "Chole-sterol": 18,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Пикша",
    "Calories": 100,
    "Caloriesتfrom Fat": 10,
    "total_fat": 2,
    "Sodium": 4,
    "Potassium": 10,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 21,
    "Vitamin A": 2,
    "Vitamin C": 0,
    "Calcium": 2,
    "تتIronتت": 6,
    "Saturated Fat": 0,
    "Chole-sterol": 23,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Палтус",
    "Calories": 120,
    "Caloriesتfrom Fat": 15,
    "total_fat": 3,
    "Sodium": 3,
    "Potassium": 14,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 23,
    "Vitamin A": 4,
    "Vitamin C": 0,
    "Calcium": 2,
    "تتIronتت": 6,
    "Saturated Fat": 0,
    "Chole-sterol": 13,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Рак",
    "Calories": 80,
    "Caloriesتfrom Fat": 0,
    "total_fat": 1,
    "Sodium": 13,
    "Potassium": 9,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 17,
    "Vitamin A": 2,
    "Vitamin C": 0,
    "Calcium": 6,
    "تتIronتت": 2,
    "Saturated Fat": 0,
    "Chole-sterol": 20,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "морской окунь",
    "Calories": 110,
    "Caloriesتfrom Fat": 20,
    "total_fat": 3,
    "Sodium": 4,
    "Potassium": 8,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 21,
    "Vitamin A": 0,
    "Vitamin C": 2,
    "Calcium": 10,
    "تتIronتت": 4,
    "Saturated Fat": 3,
    "Chole-sterol": 15,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Хоплостет",
    "Calories": 80,
    "Caloriesتfrom Fat": 5,
    "total_fat": 2,
    "Sodium": 3,
    "Potassium": 10,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 16,
    "Vitamin A": 2,
    "Vitamin C": 0,
    "Calcium": 4,
    "تتIronتت": 2,
    "Saturated Fat": 0,
    "Chole-sterol": 7,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Устрицы",
    "Calories": 100,
    "Caloriesتfrom Fat": 35,
    "total_fat": 6,
    "Sodium": 13,
    "Potassium": 6,
    "total_carbohydrate": 2,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 10,
    "Vitamin A": 0,
    "Vitamin C": 6,
    "Calcium": 6,
    "تتIronتت": 45,
    "Saturated Fat": 5,
    "Chole-sterol": 27,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Сайда",
    "Calories": 90,
    "Caloriesتfrom Fat": 10,
    "total_fat": 2,
    "Sodium": 5,
    "Potassium": 11,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 20,
    "Vitamin A": 2,
    "Vitamin C": 0,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": 0,
    "Chole-sterol": 27,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "радужная форель",
    "Calories": 140,
    "Caloriesتfrom Fat": 50,
    "total_fat": 9,
    "Sodium": 1,
    "Potassium": 11,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 20,
    "Vitamin A": 4,
    "Vitamin C": 4,
    "Calcium": 8,
    "تتIronتت": 2,
    "Saturated Fat": 10,
    "Chole-sterol": 18,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Морской окунь",
    "Calories": 110,
    "Caloriesتfrom Fat": 15,
    "total_fat": 3,
    "Sodium": 3,
    "Potassium": 13,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 21,
    "Vitamin A": 4,
    "Vitamin C": 0,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": 0,
    "Chole-sterol": 13,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Лосось",
    "Calories": 200,
    "Caloriesتfrom Fat": 90,
    "total_fat": 15,
    "Sodium": 2,
    "Potassium": 12,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 24,
    "Vitamin A": 4,
    "Vitamin C": 4,
    "Calcium": 2,
    "تتIronتت": 2,
    "Saturated Fat": 10,
    "Chole-sterol": 23,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Лосось",
    "Calories": 130,
    "Caloriesتfrom Fat": 40,
    "total_fat": 6,
    "Sodium": 3,
    "Potassium": 12,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 22,
    "Vitamin A": 2,
    "Vitamin C": 0,
    "Calcium": 2,
    "تتIronتت": 4,
    "Saturated Fat": 5,
    "Chole-sterol": 23,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Гребешки",
    "Calories": 140,
    "Caloriesتfrom Fat": 10,
    "total_fat": 2,
    "Sodium": 13,
    "Potassium": 12,
    "total_carbohydrate": 2,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 27,
    "Vitamin A": 2,
    "Vitamin C": 0,
    "Calcium": 4,
    "تتIronتت": 14,
    "Saturated Fat": 0,
    "Chole-sterol": 22,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Креветка",
    "Calories": 100,
    "Caloriesتfrom Fat": 10,
    "total_fat": 2,
    "Sodium": 10,
    "Potassium": 6,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 21,
    "Vitamin A": 4,
    "Vitamin C": 4,
    "Calcium": 6,
    "تتIronتت": 10,
    "Saturated Fat": 0,
    "Chole-sterol": 57,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Рыбы-меч",
    "Calories": 120,
    "Caloriesتfrom Fat": 50,
    "total_fat": 9,
    "Sodium": 4,
    "Potassium": 9,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 16,
    "Vitamin A": 2,
    "Vitamin C": 2,
    "Calcium": 0,
    "تتIronتت": 6,
    "Saturated Fat": 8,
    "Chole-sterol": 13,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Тилапия",
    "Calories": 110,
    "Caloriesتfrom Fat": 20,
    "total_fat": 4,
    "Sodium": 1,
    "Potassium": 10,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 22,
    "Vitamin A": 0,
    "Vitamin C": 2,
    "Calcium": 0,
    "تتIronتت": 2,
    "Saturated Fat": 5,
    "Chole-sterol": 25,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  },
  {
    "food_name": "Тунец",
    "Calories": 130,
    "Caloriesتfrom Fat": 15,
    "total_fat": 2,
    "Sodium": 2,
    "Potassium": 14,
    "total_carbohydrate": 0,
    "Dietary Fiber": "",
    "Sugars": "",
    "Protein": 26,
    "Vitamin A": 2,
    "Vitamin C": 2,
    "Calcium": 2,
    "تتIronتت": 4,
    "Saturated Fat": 0,
    "Chole-sterol": 17,
    "Food Type": "Seafood, Serving Size (84 g/3 oz)"
  }
]`;

app.all('/*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  next();
});

app.get('/insert', (req, res) => {
  var jir = req.query.jir,
      uglevod = req.query.uglevod,
      belki = req.query.belki,
      kalorii = req.query.kalorii;
  console.log(jir);
  con.query("INSERT INTO `users`(`jir`, `uglevod`, `belki`, `kalorii`) VALUES ("+jir+", "+uglevod+", "+belki+", "+kalorii+")", (err, result, fields) => {
  	console.log(result.insertId);
		res.send(JSON.stringify(result.insertId))
  })
})

app.get('/data', (req,res) => {
	var id = req.query.id
	con.query("SELECT * FROM users WHERE id = "+id, (err, result, fields) => {
		// 50, 10, 60, 1200
		var json = JSON.parse(data)
		var jir = 0,
	      uglevod = 0,
	      belki = 0;
		var kalorii = result[0].kalorii
		var count = 0;
		var product = []
		while(count < kalorii){
			var rand = randomInteger(0, json.length-1)
			console.log(json[rand].food_name);
			jir += json[rand].total_fat
			uglevod += json[rand].total_carbohydrate
			belki += json[rand].Protein
			count += json[rand].Calories
			product.push(json[rand])
		}
		console.log(count, kalorii);
		res.send(JSON.stringify(product))
	})
})

app.get('/change_product', (req, res) => {
	var json = JSON.parse(data)
	var kalorii = req.query.kalorii,
			name = req.query.name,
			now = 0,
			check = true;
	while(check){
		var rand = randomInteger(0, json.length-1)
		now = json[rand].Calories
		console.log(now);
		if(now <= kalorii+20 && now >= kalorii-20 && name !== json[rand].food_name){
			check = false
			res.send(JSON.stringify(json[rand]))
		}
	}
})

function randomInteger(min, max) {
    var rand = min - 0.5 + Math.random() * (max - min + 1)
    rand = Math.round(rand);
    return rand;
}

app.get('/get_user', (req, res) => {
  var id = req.query.id
  con.query('SELECT * FROM users WHERE id = '+id, function(err, result, fields) {
    if (!err) {
          res.send(JSON.stringify(result));
    } else {
      console.log('Error while performing Query.');
    }
  });
})

app.get('/test', (req, res) => {
  con.query('SELECT * FROM users', function(err, rows, fields) {
    if (!err) {
          res.send(JSON.stringify(rows));
    } else {
      console.log('Error while performing Query.');
    }
  });
  // res.send('test')
})

app.listen(1337, () => {
  console.log('Server listening on port 1337');
})
